#!/usr/bin/env python3
from pathlib import Path

MAX_N = 20
MAX_LEN = MAX_N // 2
WORDS = (MAX_N * MAX_N + 63) // 64
EMPTY = 65535


def placement_record(n: int, length: int, cells: list[tuple[int, int]]) -> str:
    cell_ids = [r * n + c for r, c in cells]
    padded = cell_ids + [EMPTY] * (MAX_LEN - len(cell_ids))
    bits = [0] * WORDS
    for idx in cell_ids:
        bits[idx // 64] |= 1 << (idx % 64)
    cells_s = ', '.join(str(x) for x in padded)
    bits_s = ', '.join(f'0x{x:016x}' for x in bits)
    return f'    PrecomputedPlacement {{ n: {n}, len: {length}, cells: [{cells_s}], bits: [{bits_s}] }},'


def generate() -> str:
    rows: list[str] = []
    for n in range(2, MAX_N + 1):
        for length in range(1, n // 2 + 1):
            for r in range(n):
                for c in range(n - length + 1):
                    rows.append(placement_record(n, length, [(r, c + k) for k in range(length)]))
            if length > 1:
                for r in range(n - length + 1):
                    for c in range(n):
                        rows.append(placement_record(n, length, [(r + k, c) for k in range(length)]))
    header = """// Generated by tools/generate_placement_model.py. Do not edit by hand.
#[derive(Clone, Copy)]
struct PrecomputedPlacement {
    n: u8,
    len: u8,
    cells: [u16; 10],
    bits: [u64; 7],
}

const PRECOMPUTED_PLACEMENTS: &[PrecomputedPlacement] = &[
"""
    return header + '\n'.join(rows) + "\n];\n"


def main() -> None:
    out = Path('placement_model_generated.rs')
    out.write_text(generate())
    print(f'wrote {out} ({out.stat().st_size} bytes)')


if __name__ == '__main__':
    main()
